
FROM maven:3.9.2-eclipse-temurin-17 AS builder

WORKDIR /app


COPY pom.xml .
COPY src/ ./src/


RUN mvn clean package -DskipTests


FROM openjdk:17-jdk-slim
WORKDIR /app

COPY --from=builder /app/target/taskscheduler-0.0.1-SNAPSHOT.jar scheduler.jar

CMD ["java", "-jar", "scheduler.jar", "--scheduler_port=:8081"]
