services:
  worker1:
    image: worker-image
    environment:
      - WORKER_ID=worker1
      - HOST=worker1
      - PORT=5000
    volumes:
      - worker1_storage:/app/storage
    networks:
      - app_network
    ports:
      - "5001:5000"

  worker2:
    image: worker-image
    environment:
      - WORKER_ID=worker2
      - HOST=worker2
      - PORT=5000
    volumes:
      - worker2_storage:/app/storage
    networks:
      - app_network
    ports:
      - "5002:5000"

  worker3:
    image: worker-image
    environment:
      - WORKER_ID=worker3
      - HOST=worker3
      - PORT=5000
    volumes:
      - worker3_storage:/app/storage
    networks:
      - app_network
    ports:
      - "5003:5000"

  worker4:
    image: worker-image
    environment:
      - WORKER_ID=worker4
      - HOST=worker4
      - PORT=5000
    volumes:
      - worker4_storage:/app/storage
    networks:
      - app_network
    ports:
      - "5004:5000"

  scheduler:
    image: scheduler-image
    depends_on:
      - worker1
      - worker2
      - worker3
      - worker4
    networks:
      - app_network
    ports:
      - "6000:6000"

volumes:
  worker1_storage:
  worker2_storage:
  worker3_storage:
  worker4_storage:

networks:
  app_network:
    driver: bridge
